
spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/dg_db?reWriteBatchedInserts=true&defaultSchema=dg
    username: postgres
    password: postgres
    hikari:
      connection-test-query: select 1
      minimum-idle: 1
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: dg
  flyway:
    enabled: true
    schemas: ${spring.jpa.properties.hibernate.default_schema}
    table: flyway_schema_version
server:
  port: 9002